### ISSUE TITLE
トップ画面

### ISSUE THREAD

**Issue by fruscianteee** [nekooooo0203/ChatApp#1]
## 概要
アプリが起動した時の画面

## 機能
- [x] デフォルトつぶやきが表示されている
- [x] 画面下部のメニュー
    + つぶやき、検索、チャット、通知、マイページのアイコンが表示
- [x] 検索、チャット、通知、マイページを未ログイン状態でタップすると、ログインを促すダイアログを表示する。
    + つぶやき、つぶやき詳細まで。
- [x] タブアイコンをタップした場合、その画面の一番上に行く。

**Comment by nekooooo0203** [comment]
↓↓↓↓↓　つぶやき画面に移動　↓↓↓↓↓
 つぶやきアイコンをタップするとプロフィール画面が表示
 つぶやき自体をタップすると、つぶやき詳細画面に遷移
 つぶやきに対してリプライボタンをタップすると、
未ログイン時はログイン画面
ログイン時はつぶやきの作成画面
 下に引っ張ると、つぶやき更新
 つぶやきの間に広告あり。
 つぶやきのメニューをタップすると、通報とブロックのメニューを表示
 画面右下につぶやきのフローボタンを配置。

**Comment by nekooooo0203** [comment]
相手の、プロフィール、チャット押す　→　ログイン促す

**Comment by nekooooo0203** [comment]
タブボタンをタップした場合、その画面の一番上に行く。

**Comment by nekooooo0203** [comment]
通知？などがあった場合に、タブのアイコンにバッジ/色変更する。
⇒　バッジを定期的に取得する。
⇒　リロードは各自
