### ISSUE TITLE
相互チャットリスト画面 - 相互チャット画面

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#11]
## 概要
相互チャット画面

## 機能
- [x] チャット画面が表示されている
    + 画像、名前、メニューボタン、メッセージ一覧、画像ボタン、テキスト入力、送信ボタン、（スタンプ）
- [x] バナー広告
- [x] メニューボタンは、ブロック、通報ボタン
- [x] メッセージ一覧は、上が新しく、下が古いメッセージ
- [x] メッセージ一覧は、左が相手、右が自分
- [x] メッセージ一覧は、自動更新
- [x] 相手側のメッセージ毎の左側に相手のプロフィールアイコンを表示する。
- [ ] （見送り）画像ボタンで、画像を選択し、送信できる。
- [x] テキストを入力し、送信ボタンを押すことで、新規メッセージが送信される。
- [x] ブロック解除した場合は、ブロックした時間以降のメッセージのみ表示される。
- [ ] 
- [ ]

**Comment by fruscianteee** [comment]
・画像ボタンの実装は初回リリースでは見送ります。

相手のプロフィールのアイコンを表示したいです。以下のいずれかにしたいと思っています。
いかがでしょうか。
・画面上部にヘッダーを用意して相手のプロフィールアイコンと名前が表示する。
・相手側のメッセージ毎の左側に相手のプロフィールアイコンを表示する。

**Comment by nekooooo0203** [comment]
・画面上部にヘッダーを用意して相手のプロフィールアイコンと名前を表示する。
・相手側のメッセージ毎の左側に相手のプロフィールアイコンを表示する。

両方ともできますが、プロフィールアイコンが見えたほうが相手のことを意識しやすい？
と思うので、
・相手側のメッセージ毎の左側に相手のプロフィールアイコンを表示する。
で実装したいと思います。
