### ISSUE TITLE
マイページ設定 - プロフィール編集

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#13]
## 概要
名前だけ登録していれば、OK。

## 仕様
- [x] プロフィール情報：名前、年齢、場所、自己紹介、性別、プロフィール画像
- [x] 戻るボタンを押すと、前の画面に戻る
- [x] 画面右上の完了ボタンを押すと、更新される。
- [x] 画像を押すと、カメラ、フォルダから画像を選択できる
    + 選択後、正方形に切り抜き、完了することで画像が更新される
- [x] 名前　１－２０文字
- [x] 年齢　１８－99歳　＆　未設定
- [x] 場所　都道府県　＆　未設定
- [x] 自己紹介　０－１００文字
- [x] 性別　男、女、未設定

**Comment by fruscianteee** [comment]
年齢は18-99歳までにします。

自己紹介文は100文字まででOKです。
