### ISSUE TITLE
設定 - お問い合わせ

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#14]
## 概要
 お問い合わせ

## 仕様
- [x] トピックが選択できる
    + 古いアカウントを削除したい
    + プロフィール写真が削除された
    + アカウントが削除された
    + 質問
    + 要望
    + 不具合報告
    + メディア
    + その他
- [x] 内容

**Comment by fruscianteee** [comment]
送信時は、
送信者のUID、トピック、内容、送信日時
をfirestoreへ残す

**Comment by nekooooo0203** [comment]
↓　　は　通報の場所に。

業者を発見
不適切な画像
セクハラ行為
不適切な言動
