### ISSUE TITLE
ログイン画面

### ISSUE THREAD

**Issue by fruscianteee** [nekooooo0203/ChatApp#2]
## 概要
SMS認証、Google認証の2つの認証をする。

## 機能
- [x] SMS認証の場合、(仮定)
1. 電話番号を入力させて、SMS送信ボタンをタップさせる。
2-1. 認証用のSMSが届いて、そのURLをユーザが開くことで、登録する。(仮定)
3-1.  ユーザがアプリに戻ると、手順1の画面がマイページに進む。
4-1. マイページ情報を登録して、保存する。

2-2. 認証用のSMSが届いて、その番号を入力することで、Firebase Auth に登録/ログイン
3-2. マイページに進み、マイページ情報を登録して、保存する。（）

- [x] Google認証の場合、
1. Google認証用のボタンをタップ。
2. 端末でログインしていなかったら、googleのログインに遷移。
3. ログインしたら、アプリに戻り、ログインしましたを表示。「続けて登録ボタン」を表示。
4. 「続けて登録ボタン」マイページに移動。
5. マイページ情報を登録して、保存する。

- [x] 確認ダイアログを表示 →ユーザー新規作成時

**Comment by fruscianteee** [comment]
上記のボタンを押下した時に、または、この画面を開いた場合に、確認ダイアログを表示します。
　例：18歳未満はダメですよ、犯罪ですよ、保証しませんよ、卑猥な写真はダメですよなどの、云々かんぬんメッセージと[キャンセル][同意]ボタンを表示。

**Comment by nekooooo0203** [comment]
18歳以下同意firestore に保存
