### ISSUE TITLE
中華フォント対策

### ISSUE THREAD

**Issue by fruscianteee** [nekooooo0203/ChatApp#22]
https://e-keiai.com/archives/157

**Comment by nekooooo0203** [comment]
https://pub.dev/packages/get#internationalization
https://iisprey.medium.com/change-your-app-language-dynamically-with-getx-in-flutter-75876db76aed

**Comment by nekooooo0203** [comment]
☆https://flutter.dev/docs/development/accessibility-and-localization/internationalization#setting-up
・pubspec.yaml
  flutter_localizations:
    sdk: flutter
・MaterialAppの場所に
 localizationsDelegates: [
   GlobalMaterialLocalizations.delegate,
   GlobalWidgetsLocalizations.delegate,
   GlobalCupertinoLocalizations.delegate,
 ],
 supportedLocales: [
    const Locale('en', ''), // English, no country code
    const Locale('ja', 'JP'), // country code ?????
    // ... other locales the app supports
  ],

☆https://iisprey.medium.com/change-your-app-language-dynamically-with-getx-in-flutter-75876db76aed
・Folder
lang
┗en_us.dart
┗ja_jp.dart

・const Map<String, String> enUS = {
  'hello': 'Hello!',
};

class LocalizationService extends Translations {

・MaterialAppの場所に
      locale: LocalizationService.locale,
      fallbackLocale: LocalizationService.fallbackLocale,
      translations: LocalizationService(),

**Comment by nekooooo0203** [comment]
https://e-keiai.com/archives/157
を採用
