### ISSUE TITLE
リプライ一覧

### ISSUE THREAD

**Issue by fruscianteee** [nekooooo0203/ChatApp#28]
- [x] 表示順番を上から最新にする

----------------追加--------------
リプライ一覧（つぶやき詳細）⇒ひっぱると取得できるように。　 #79 対応

**Comment by nekooooo0203** [comment]
つぶやき詳細⇒ひっぱると取得できるように。

**Comment by nekooooo0203** [comment]
Refresh Controller Service
onRefresh → Newer Tweet
onLoading → Older Tweet 
最初に表示するデータは
タップされたデータ
＋New５件＋Old５件分

**Comment by nekooooo0203** [comment]
Body
          future: TweetDetailFunction.getOlderThread(context),
Fire store Service 
  Future<Tuple2<List<DocumentSnapshot>, String>> getTweetThread(
    if (newToldF) {
          .orderBy(dbCreatedAt, descending: false) → true

**Comment by nekooooo0203** [comment]
上二つ、コミットをキャンセルし、再度コミットを行う
