### ISSUE TITLE
マイページ画面

### ISSUE THREAD

**Issue by fruscianteee** [nekooooo0203/ChatApp#3]
## 概要
名前だけ登録していれば、OK。

## 仕様
- [x] プロフィール情報：プロフィール画像、名前、年齢、場所、自己紹介
- [x] 自身のつぶやきを表示されている。
    + つぶやきをタップすると、つぶやき詳細画面へ遷移。
- [x] プロフィール編集ボタンがある。
- [x] 広告を表示。
- [x] 画面右上に歯車アイコンをタップすると、設定やアプリ関連の一覧画面に遷移。

**Comment by nekooooo0203** [comment]
自己紹介追加
