### ISSUE TITLE
検索画面

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#6]
## 概要
ユーザーを検索できる画面

## 機能
- [x] 数人の簡易プロフィールが表示されている（ブロックユーザー表示しない）
    + 画像、名前、場所、年齢
- [x] 簡易プロフィールをタップすると、該当ユーザーのプロフィール画面に遷移
- [x] 画面上部にバナー広告
- [x] フロートボタンを押すと、検索設定ダイアログが表示される
- [x] 検索設定ダイアログで、検索するを押すと、該当するデータのユーザーが表示される
     + 性別、年齢、場所、

**Comment by fruscianteee** [comment]
広告は画面上部にバナー広告で。

**Comment by nekooooo0203** [comment]
ブロック、タブごとにブロックした場合、元のタブに戻る
⇒　戻ったタブで、更新
