### ISSUE TITLE
相互チャットリスト画面

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#7]
## 概要
人とチャットできる部屋のリスト

## 機能
- [x] チャット中の部屋が表示されている（ブロックユーザー表示しない）
    + 画像、名前、最後のメッセージ
- [x] チャット部屋をタップすると、該当部屋の相互チャット画面に遷移
- [ ] (実装保留)リストの右上に編集ボタンがあり、ボタンを押し、部屋の管理（削除）ができる
- [x] Stream(自動更新)
- [ ] (保留)下にスクロールで更新（Future builder）
　→　差分取得
- [x] メッセージがない場合は、リストに表示しない。
- [x] 既読

**Comment by fruscianteee** [comment]
部屋の管理（削除）については、もう少し仕様を考えた方が良いため、一旦実装保留でお願いします。

**Comment by nekooooo0203** [comment]
チャットに関して、バッジをつくる
引っ張って更新、チャットタブをタップで更新

**Comment by nekooooo0203** [comment]
引っ張って更新もできるようにしておく？
懸念点・・・？

**Comment by nekooooo0203** [comment]
部屋作った場合、作ってもいいけど、メッセージない場合は、、表示しない。

**Comment by nekooooo0203** [comment]
スライドできるようにする。
ブロック、

**Comment by nekooooo0203** [comment]
相手の、プロフィール、チャット押す　→　ログイン促す
