### ISSUE TITLE
通知画面

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#8]
## 概要
アプリの通知を確認できる画面

## 機能
- [x] 上部に、 運営側の通知、つぶやきのリプライ、足跡のタブ
- [x] 足跡は、プロフィールを表示したユーザーが表示される。

**Comment by fruscianteee** [comment]
お知らせタブは、
つぶやきのリプライ、
運営側の通知、
の認識であれば、それで実装でお願いします。

足跡に関しては、初めて閲覧したユーザだった場合のみ、残しましょうか。
足跡のデータは、UID、名前、閲覧日あたりだと思いますが、
他にもあればアレンジをお願いします。

**Comment by nekooooo0203** [comment]
運営通知　→　画面遷移あり。
